config/routes.rb
Rails.application.routes.draw do
  resources :saved_searches, only: [:destroy]
end

app/models/saved_search.rb
class SavedSearch < ActiveRecord::Base
  validates_presence_of :context, :description, :search_params

  serialize :search_params
end

app/controllers/concerns/ransack_advanced_search/saved_search_utils.rb
module RansackAdvancedSearch
  module SavedSearchUtils
    extend ActiveSupport::Concern

    # Perform saved searches actions to provide full functionality with one method
    def perform_saved_searches_actions(context, params={})
      get_saved_searches(context)
      save_or_update_saved_search(params.merge(context: context))
      get_params_to_search(context)
    end

    # Get list of Saved Search by context
    def get_saved_searches(context)
      @saved_searches = SavedSearch.where(context: context)
    end

    # Return params of Saved Search or search form params
    def get_params_to_search(context)
      if params[:saved_search].present?
        @saved_search = SavedSearch.find_by(id: params[:saved_search], context: context)
      end
      return params[:q] if params[:use_search_params].present?
      params[:q] = @saved_search.try(:search_params) || params[:q]
    end

    # Save or update Saved Search
    def save_or_update_saved_search(params)
      if params[:save_new_search].present? || params[:save_search].present?
        if params[:save_new_search].present?
          @saved_search = new_saved_search(params)
        elsif params[:save_search].present? && params[:saved_search].present?
          @saved_search = update_saved_search(params)
        elsif params[:save_search].present?
          @saved_search = new_saved_search(params)
        end

        if @saved_search.save
          flash[:notice] = t('ransack.saved_search.save.success')
        else
          flash[:error] = t('ransack.saved_search.save.error')
        end
      end
    end

    def new_saved_search(params)
      SavedSearch.new(
       context: params[:context], description: params[:description],
       search_params: params[:q]
      )
    end

    def update_saved_search(params)
      saved_search = SavedSearch.find_by(id: params[:saved_search], context: params[:context])
      saved_search.description = params[:description]
      saved_search.search_params = params[:q]
      saved_search
    end
  end
end

app/controllers/ransack_advanced_search/application_controller.rb
module RansackAdvancedSearch
  class ApplicationController < ActionController::Base
    protect_from_forgery :with => :exception
  end
end

app/controllers/saved_searches_controller.rb
class SavedSearchesController < ApplicationController
  before_action :set_saved_search, only: [:destroy]

  # DELETE /saved_search/1
  # DELETE /saved_search/1.json
  def destroy
    @saved_search.destroy
    respond_to do |format|
      redirect_path = params[:redirect_to] || root_path
      format.html { redirect_to redirect_path, notice: t('ransack.saved_search.delete.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saved_search
      @saved_search = SavedSearch.find(params[:id])
    end
end

app/helpers/ransack_advanced_search_helper.rb
module RansackAdvancedSearchHelper
  def setup_search_form(builder, search_object)
    fields = builder.grouping_fields builder.object.new_grouping,
      object_name: 'new_object_name', child_index: "new_grouping" do |f|
      render('ransack_advanced_search/grouping_fields', f: f)
    end
    content_for :ransack_setup, %Q{
      var search = new Search({grouping: "#{escape_javascript(fields)}"});
      search.fieldsType = #{get_fields_data_type(search_object).to_json.html_safe}
      $('select.ransack-attribute-select').each(function(e) {
        fieldName = $(this).find('option:selected')[0].value;
        search.changeValueInputsType(this, fieldName, search);
      });
      $(document).on("click", "i.add_fields", function() {
        search.add_fields(this, $(this).data('fieldType'), $(this).data('content'));
        if($(this).hasClass('ransack-add-attribute')) {
          fieldName = $(this).parents('.ransack-condition-field').find('select.ransack-attribute-select').find('option:selected')[0].value;
          search.changeValueInputsType(this, fieldName, search);
        }
        return false;
      });
      $(document).on('change', 'select.ransack-attribute-select', function(e) {
        fieldName = $(this).find('option:selected')[0].value;
        search.changeValueInputsType(this, fieldName, search);
      });
      $(document).on("click", "i.remove_fields", function() {
        search.remove_fields(this);
        return false;
      });
      $(document).on("click", "button.nest_fields", function() {
        search.nest_fields(this, $(this).data('fieldType'));
        return false;
      });
    }.html_safe
  end

  def get_fields_data_type(search)
    bases = [''] + search.klass.ransackable_associations
    fields_type = Hash.new
    bases.each do |model|
      model_name = model.present? ? "#{model}_" : ""
      search.context.traverse(model).columns_hash.each do |field, attributes|
        fields_type["#{model_name}#{field}"] = attributes.type
      end
    end
    fields_type
  end

  def button_to_remove_fields
    content_tag :i, nil, class: 'remove_fields glyphicon glyphicon-minus-sign text-danger'
  end

  def button_to_add_fields(name, f, type, custom_class='')
    new_object = f.object.send "build_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: "new_#{type}") do |builder|
      render('ransack_advanced_search/' + type.to_s + "_fields", f: builder)
    end
    content_tag :i, name, :class => custom_class + ' add_fields glyphicon glyphicon-plus-sign text-success', :type => 'button', 'data-field-type' => type, 'data-content' => "#{fields}"
  end

  def button_to_nest_fields(name, type)
    content_tag :button, name, :class => 'nest_fields', 'data-field-type' => type
  end
end

app/views/ransack_advanced_search/_advanced_search.html.erb
<div class="ransack-advanced-search">

  <div class="row">
  <% if RansackAdvancedSearch.enable_saved_searches %>
    <div class="col-md-4">
      <%= render 'ransack_advanced_search/saved_searches_list', redirect_path: redirect_path %>
    </div>
    <div class="col-md-8">
  <% else %>
    <div class="col-md-12">
  <% end %>
      <%= search_form_for(@search, url: search_url, html: { method: :post, class: 'form-inline', role: 'form'  }) do |f| %>

        <% setup_search_form f, @search %>

        <% if RansackAdvancedSearch.enable_saved_searches %>
          <div class="form-group">
            <%= label_tag 'Descrição da Busca (necessária para salvar a busca)' %>
            <%= text_field_tag :description, @saved_search.try(:description), class: 'form-control input-sm' %>
            <% if @saved_search %>
              <%= hidden_field_tag :saved_search, @saved_search.id %>
              <%= hidden_field_tag :use_search_params, true %>
            <% end %>
          </div>
        <% end %>

        <h4><%= t('ransack.advanced_search.sort.title') %></h4>
        <div class="form-group">
          <%= f.sort_fields do |s| %>
            <%= render 'ransack_advanced_search/sort_fields', f: s %>
          <% end %>
          <%= button_to_add_fields '', f, :sort %>
        </div>

        <h4><%= t('ransack.advanced_search.condition_group.title') %></h4>
        <div class="form-group">
          <%= f.grouping_fields do |g| %>
            <%= render 'ransack_advanced_search/grouping_fields', f: g %>
          <% end %>
          <%= button_to_add_fields '', f, :grouping %>
        </div>

        <!-- <%= label_tag :distinct, 'Return distinct records?' %> -->
        <!-- <%= check_box_tag :distinct, '1', params[:distinct].to_i == 1 %> -->
        <div class="clearfix"></div>
        <div class="ransack-action-buttons">
          <%= f.submit t('ransack.advanced_search.form.submit_text'), class: 'btn btn-primary' %>
          <% if RansackAdvancedSearch.enable_saved_searches %>
            <%= f.submit t('ransack.advanced_search.form.save_submit_text'), name: 'save_search', class: 'btn btn-primary' %>
            <%= f.submit t('ransack.advanced_search.form.save_new_submit_text'), name: 'save_new_search', class: 'btn btn-primary' %>
          <% end %>
          <%= link_to t('ransack.advanced_search.form.clear_search_text'), redirect_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:ransack_advanced_search_setup) do %>
  <%= stylesheet_link_tag 'ransack_advanced_search/application', media: 'all' %>
  <%= javascript_include_tag 'ransack_advanced_search/application' %>

  <script>
    $(document).ready(function () {
      <%= yield(:ransack_setup) %>
    });
  </script>
<% end %>

app/views/ransack_advanced_search/_attribute_fields.erb
<%= content_tag(:span,
  f.attribute_select({associations: @search.klass.ransackable_associations}, {class: 'ransack-attribute-select form-control input-sm'}),
  { class: 'fields', 'data-object-name' => f.object_name }, false) %>

app/views/ransack_advanced_search/_condition_fields.erb
<%= content_tag :div, {
  class: 'fields condition ransack-condition-field', 'data-object-name' => f.object_name
  } do %>

  <%= content_tag(:span, button_to_remove_fields, {}, false) %>

  <%= f.attribute_fields do |a| %>
    <%= render 'ransack_advanced_search/attribute_fields', f: a %>
  <% end %>

  <%= f.predicate_select({}, {class: 'form-control input-sm'}) %>

  <%= f.value_fields do |v| %>
    <%= render 'ransack_advanced_search/value_fields', f: v %>
  <% end %>

  <%= button_to_add_fields '', f, :value, 'ransack-add-attribute' %>

<% end %>

app/views/ransack_advanced_search/_grouping_fields.erb
<%= content_tag :div, { class: 'fields', 'data-object-name' => f.object_name } do %>

  <% remove_able = true if local_assigns[:remove_able].nil? %>
  <% if remove_able == false %>
    <%= content_tag(:span, "#{t('ransack.advanced_search.condition_group.match')}
      #{f.combinator_select({}, {class: 'form-control input-sm'})}
      #{t('ransack.advanced_search.condition_group.match_condition')}", nil, false) %>
  <% else %>
    <%= content_tag(:span, "#{t('ransack.advanced_search.condition_group.match')}
      #{f.combinator_select({}, {class: 'form-control input-sm'})} #{t('ransack.advanced_search.condition_group.match_condition')}
      #{button_to_remove_fields}", nil, false) %>
  <% end %>

  <% condition_fields = f.condition_fields do |c| %>
    <%= render 'ransack_advanced_search/condition_fields', f: c %>
  <% end %>
  <%= condition_fields %>
  <% if condition_fields.empty? %>
    <%= f.send("condition_fields", f.object.send("build_condition"), child_index: "new_condition") do |builder| %>
      <%= render 'ransack_advanced_search/condition_fields', f: builder %>
    <% end %>
  <% end %>

  <%= button_to_add_fields '', f, :condition %>

  <%= f.grouping_fields do |g| %>
    <%= render partial: 'ransack_advanced_search/grouping_fields',
               locals: { f: g, remove_able: true } %>
  <% end %>

<% end %>

app/views/ransack_advanced_search/_quick_search.html.erb
<div class="ransack-advanced-search">

  <div class="row">
  <% if RansackAdvancedSearch.enable_saved_searches %>
    <div class="col-md-4">
      <%= render 'ransack_advanced_search/saved_searches_list', redirect_path: redirect_path %>
    </div>
    <div class="col-md-8">
  <% else %>
    <div class="col-md-12">
  <% end %>
      <%= search_form_for(@search, url: search_url, html: { method: :post, class: 'form-inline', role: 'form'  }) do |f| %>
        <% setup_search_form f, @search %>

        <% if RansackAdvancedSearch.enable_saved_searches %>
          <div class="form-group">
            <%= label_tag 'Descrição da Busca (necessária para salvar a busca)' %>
            <%= text_field_tag :description, @saved_search.try(:description), class: 'form-control input-sm' %>
            <% if @saved_search %>
              <%= hidden_field_tag :saved_search, @saved_search.id %>
              <%= hidden_field_tag :use_search_params, true %>
            <% end %>
          </div>
        <% end %>

        <h4><%= t('ransack.quick_search.condition_group.title') %></h4>
        <div class="form-group">
          <% if f.grouping_fields.empty? %>
            <%= render partial: 'ransack_advanced_search/grouping_fields',
                       locals: { f: f, remove_able: false } %>
          <% else %>
            <%= f.grouping_fields do |g| %>
              <%= render partial: 'ransack_advanced_search/grouping_fields',
                         locals: { f: f, remove_able: true } %>
            <% end %>
            <%= button_to_add_fields '', f, :grouping %>
          <% end %>
        </div>

        <div class="clearfix"></div>
        <div class="ransack-action-buttons">
          <%= f.submit t('ransack.advanced_search.form.submit_text'), class: 'btn btn-primary' %>
          <% if RansackAdvancedSearch.enable_saved_searches %>
            <%= f.submit t('ransack.advanced_search.form.save_submit_text'), name: 'save_search', class: 'btn btn-primary' %>
            <%= f.submit t('ransack.advanced_search.form.save_new_submit_text'), name: 'save_new_search', class: 'btn btn-primary' %>
          <% end %>
          <%= link_to t('ransack.advanced_search.form.clear_search_text'), redirect_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for(:ransack_advanced_search_setup) do %>
  <%= stylesheet_link_tag 'ransack_advanced_search/application', media: 'all' %>
  <%= javascript_include_tag 'ransack_advanced_search/application' %>

  <script>
    $(document).ready(function () {
      <%= yield(:ransack_setup) %>
    });
  </script>
<% end %>

app/views/ransack_advanced_search/_saved_searches_list.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= t('ransack.saved_search.title') %></div>
  <ul class="list-group lista-buscas">
    <% @saved_searches.each do |saved_search| %>
      <li class="list-group-item">
        <%= link_to url_for(saved_search: saved_search.id), method: :post do %>
          <%= saved_search.description %>
        <% end %>
        <div class="pull-right ransack-saved-search-delete">
          <%= link_to saved_search_path(id: saved_search.id, redirect_to: redirect_path),
              { method: :delete, title: t('ransack.advanced_search.form.delete_saved_search'),
                data: { confirm: t('ransack.advanced_search.form.delete_saved_search_confirm'),
                toggle: 'tooltip', placement: 'bottom' } } do %>
            <icon class="glyphicon glyphicon-trash text-danger"></i>
          <% end %>
        </div>
      </li>
    <% end %>
    <% if @saved_searches.empty? %>
      <li class="list-group-item">
        <em><%= t('ransack.saved_search.empty_list') %></em>
      </li>
    <% end %>
  </ul>
</div>

app/views/ransack_advanced_search/_sort_fields.erb
<%= content_tag(:div,
  "#{button_to_remove_fields} #{f.sort_select({}, {class: 'form-control input-sm'})}",
  { class: 'fields', 'data-object-name' => f.object_name }, false) %>

app/views/ransack_advanced_search/_value_fields.erb
<%= content_tag(:span, f.text_field(:value, {class: 'form-control input-sm ransack-attribute-value'}),
  { class: 'fields value', 'data-object-name' => f.object_name }, false) %>